--------------------------------------------------------
--  ファイルを作成しました - 月曜日-11月-09-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table D_ENTRY
--------------------------------------------------------

  CREATE TABLE "D_ENTRY" 
   (	"ENTRY_UNIT_ID" CHAR(35 BYTE), 
	"RECORD_KBN" CHAR(1 BYTE), 
	"IMAGE_SEQ" NUMBER(4,0), 
	"ITEM_ID" CHAR(8 BYTE), 
	"VALUE" NVARCHAR2(4000), 
	"OCR_VALUE" NVARCHAR2(4000), 
	"OCR_IMPORT_FLAG" CHAR(1 BYTE) DEFAULT '0', 
	"NO_ENTRY_ITEM_FLAG" CHAR(1 BYTE) DEFAULT '0', 
	"DUMMY_ITEM_FLAG" CHAR(1 BYTE) DEFAULT '0', 
	"DIFF_FLAG" CHAR(1 BYTE) DEFAULT '0', 
	"INS_USER_ID" VARCHAR2(30 BYTE), 
	"INS_DATE" DATE DEFAULT sysdate, 
	"UPD_USER_ID" VARCHAR2(30 BYTE), 
	"UPD_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;

   COMMENT ON COLUMN "D_ENTRY"."ENTRY_UNIT_ID" IS 'エントリユニットID';
   COMMENT ON COLUMN "D_ENTRY"."RECORD_KBN" IS 'レコード区分';
   COMMENT ON COLUMN "D_ENTRY"."IMAGE_SEQ" IS '画像SEQ';
   COMMENT ON COLUMN "D_ENTRY"."ITEM_ID" IS '項目ID';
   COMMENT ON COLUMN "D_ENTRY"."VALUE" IS '値';
   COMMENT ON COLUMN "D_ENTRY"."OCR_VALUE" IS 'OCR値';
   COMMENT ON COLUMN "D_ENTRY"."OCR_IMPORT_FLAG" IS 'OCR取込フラグ';
   COMMENT ON COLUMN "D_ENTRY"."NO_ENTRY_ITEM_FLAG" IS '入力無し項目フラグ';
   COMMENT ON COLUMN "D_ENTRY"."DUMMY_ITEM_FLAG" IS 'ダミー項目フラグ';
   COMMENT ON COLUMN "D_ENTRY"."DIFF_FLAG" IS '差異有りフラグ';
   COMMENT ON COLUMN "D_ENTRY"."INS_USER_ID" IS '登録ユーザID';
   COMMENT ON COLUMN "D_ENTRY"."INS_DATE" IS '登録日時';
   COMMENT ON COLUMN "D_ENTRY"."UPD_USER_ID" IS '更新ユーザID';
   COMMENT ON COLUMN "D_ENTRY"."UPD_DATE" IS '更新日時';
   COMMENT ON TABLE "D_ENTRY"  IS 'エントリ';
--------------------------------------------------------
--  DDL for Table D_ENTRY_STATUS
--------------------------------------------------------

  CREATE TABLE "D_ENTRY_STATUS" 
   (	"ENTRY_UNIT_ID" CHAR(35 BYTE), 
	"RECORD_KBN" CHAR(1 BYTE), 
	"OCR_IMPORT_USER_ID" VARCHAR2(30 BYTE), 
	"ENTRY_USER_ID" VARCHAR2(30 BYTE), 
	"ENTRY_STATUS" CHAR(1 BYTE) DEFAULT '0', 
	"ENTRY_START_TIME" DATE, 
	"ENTRY_END_TIME" DATE, 
	"INS_USER_ID" VARCHAR2(30 BYTE), 
	"INS_DATE" DATE DEFAULT sysdate, 
	"UPD_USER_ID" VARCHAR2(30 BYTE), 
	"UPD_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;

   COMMENT ON COLUMN "D_ENTRY_STATUS"."ENTRY_UNIT_ID" IS 'エントリユニットID';
   COMMENT ON COLUMN "D_ENTRY_STATUS"."RECORD_KBN" IS 'レコード区分';
   COMMENT ON COLUMN "D_ENTRY_STATUS"."OCR_IMPORT_USER_ID" IS 'OCR結果取込みユーザID';
   COMMENT ON COLUMN "D_ENTRY_STATUS"."ENTRY_USER_ID" IS 'エントリユーザID';
   COMMENT ON COLUMN "D_ENTRY_STATUS"."ENTRY_STATUS" IS 'エントリ状態';
   COMMENT ON COLUMN "D_ENTRY_STATUS"."ENTRY_START_TIME" IS 'エントリ開始時刻';
   COMMENT ON COLUMN "D_ENTRY_STATUS"."ENTRY_END_TIME" IS 'エントリ終了時刻';
   COMMENT ON COLUMN "D_ENTRY_STATUS"."INS_USER_ID" IS '登録ユーザID';
   COMMENT ON COLUMN "D_ENTRY_STATUS"."INS_DATE" IS '登録日時';
   COMMENT ON COLUMN "D_ENTRY_STATUS"."UPD_USER_ID" IS '更新ユーザID';
   COMMENT ON COLUMN "D_ENTRY_STATUS"."UPD_DATE" IS '更新日時';
   COMMENT ON TABLE "D_ENTRY_STATUS"  IS 'エントリ状況';
--------------------------------------------------------
--  DDL for Table D_ENTRY_UNIT
--------------------------------------------------------

  CREATE TABLE "D_ENTRY_UNIT" 
   (	"TKSK_CD" CHAR(6 BYTE), 
	"HNM_CD" CHAR(3 BYTE), 
	"IMAGE_CAPTURE_DATE" CHAR(8 BYTE), 
	"IMAGE_CAPTURE_NUM" CHAR(2 BYTE), 
	"DOC_ID" CHAR(8 BYTE), 
	"ENTRY_UNIT" CHAR(3 BYTE), 
	"STATUS" CHAR(1 BYTE) DEFAULT '0', 
	"OCR_IMPORT_USER_ID" VARCHAR2(30 BYTE), 
	"UPD_ENTRY_USER_ID" VARCHAR2(30 BYTE), 
	"UPD_ENTRY_START_TIME" DATE, 
	"UPD_ENTRY_END_TIME" DATE, 
	"VERIFY_ENTRY_USER_ID" VARCHAR2(30 BYTE), 
	"VERIFY_ING_FLAG" CHAR(1 BYTE) DEFAULT '0', 
	"ENTRY_END_DATE" DATE, 
	"TEXT_EXPORT_DATE" DATE, 
	"ENTRY_UNIT_ID" CHAR(35 BYTE), 
	"INS_USER_ID" VARCHAR2(30 BYTE), 
	"INS_DATE" DATE DEFAULT sysdate, 
	"UPD_USER_ID" VARCHAR2(30 BYTE), 
	"UPD_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;

   COMMENT ON COLUMN "D_ENTRY_UNIT"."TKSK_CD" IS '得意先コード';
   COMMENT ON COLUMN "D_ENTRY_UNIT"."HNM_CD" IS '品名コード';
   COMMENT ON COLUMN "D_ENTRY_UNIT"."IMAGE_CAPTURE_DATE" IS 'イメージ連携年月日';
   COMMENT ON COLUMN "D_ENTRY_UNIT"."IMAGE_CAPTURE_NUM" IS 'イメージ連携回数';
   COMMENT ON COLUMN "D_ENTRY_UNIT"."DOC_ID" IS '帳票ID';
   COMMENT ON COLUMN "D_ENTRY_UNIT"."ENTRY_UNIT" IS 'ユニット';
   COMMENT ON COLUMN "D_ENTRY_UNIT"."STATUS" IS 'ユニットステータス';
   COMMENT ON COLUMN "D_ENTRY_UNIT"."OCR_IMPORT_USER_ID" IS 'OCR結果取込みユーザID';
   COMMENT ON COLUMN "D_ENTRY_UNIT"."UPD_ENTRY_USER_ID" IS '修正ユーザID';
   COMMENT ON COLUMN "D_ENTRY_UNIT"."UPD_ENTRY_END_TIME" IS '入力終了日時（コンペア済日時）
';
   COMMENT ON COLUMN "D_ENTRY_UNIT"."VERIFY_ENTRY_USER_ID" IS '検証ユーザID';
   COMMENT ON COLUMN "D_ENTRY_UNIT"."TEXT_EXPORT_DATE" IS 'テキスト出力日時';
   COMMENT ON COLUMN "D_ENTRY_UNIT"."ENTRY_UNIT_ID" IS 'エントリユニットID';
   COMMENT ON COLUMN "D_ENTRY_UNIT"."INS_USER_ID" IS '登録ユーザID';
   COMMENT ON COLUMN "D_ENTRY_UNIT"."INS_DATE" IS '登録日時';
   COMMENT ON COLUMN "D_ENTRY_UNIT"."UPD_USER_ID" IS '更新ユーザID';
   COMMENT ON COLUMN "D_ENTRY_UNIT"."UPD_DATE" IS '更新日時';
   COMMENT ON TABLE "D_ENTRY_UNIT"  IS 'エントリユニット';
--------------------------------------------------------
--  DDL for Table D_IMAGE_INFO
--------------------------------------------------------

  CREATE TABLE "D_IMAGE_INFO" 
   (	"ENTRY_UNIT_ID" CHAR(35 BYTE), 
	"IMAGE_SEQ" NUMBER(4,0), 
	"IMAGE_PATH" VARCHAR2(512 BYTE), 
	"RECORD_KBN_0_ENTRY_FLAG" CHAR(1 BYTE) DEFAULT '0', 
	"RECORD_KBN_1_ENTRY_FLAG" CHAR(1 BYTE) DEFAULT '0', 
	"RECORD_KBN_2_ENTRY_FLAG" CHAR(1 BYTE) DEFAULT '0', 
	"OCR_IMPORT_DATE" DATE, 
	"OCR_IMAGE_FILE_NAME" VARCHAR2(255 BYTE), 
	"DUMMY_IMAGE_FLAG" CHAR(1 BYTE) DEFAULT '0', 
	"OCR_NG_STATUS" CHAR(3 BYTE) DEFAULT NULL, 
	"INS_USER_ID" VARCHAR2(30 BYTE), 
	"INS_DATE" DATE DEFAULT sysdate, 
	"UPD_USER_ID" VARCHAR2(30 BYTE), 
	"UPD_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;

   COMMENT ON COLUMN "D_IMAGE_INFO"."ENTRY_UNIT_ID" IS 'エントリユニットID';
   COMMENT ON COLUMN "D_IMAGE_INFO"."IMAGE_SEQ" IS 'イメージSEQ';
   COMMENT ON COLUMN "D_IMAGE_INFO"."IMAGE_PATH" IS 'イメージパス';
   COMMENT ON COLUMN "D_IMAGE_INFO"."RECORD_KBN_0_ENTRY_FLAG" IS 'コンペア入力済フラグ';
   COMMENT ON COLUMN "D_IMAGE_INFO"."RECORD_KBN_1_ENTRY_FLAG" IS '１人目入力済フラグ';
   COMMENT ON COLUMN "D_IMAGE_INFO"."RECORD_KBN_2_ENTRY_FLAG" IS '２人目入力済フラグ';
   COMMENT ON COLUMN "D_IMAGE_INFO"."OCR_IMPORT_DATE" IS 'OCR取込年月日';
   COMMENT ON COLUMN "D_IMAGE_INFO"."OCR_IMAGE_FILE_NAME" IS 'OCR連携ファイル名';
   COMMENT ON COLUMN "D_IMAGE_INFO"."DUMMY_IMAGE_FLAG" IS 'ダミーイメージフラグ';
   COMMENT ON COLUMN "D_IMAGE_INFO"."OCR_NG_STATUS" IS '論理チェックステータス';
   COMMENT ON COLUMN "D_IMAGE_INFO"."INS_USER_ID" IS '登録ユーザID';
   COMMENT ON COLUMN "D_IMAGE_INFO"."INS_DATE" IS '登録日時';
   COMMENT ON COLUMN "D_IMAGE_INFO"."UPD_USER_ID" IS '更新ユーザID';
   COMMENT ON COLUMN "D_IMAGE_INFO"."UPD_DATE" IS '更新日時';
   COMMENT ON TABLE "D_IMAGE_INFO"  IS '画像情報';
--------------------------------------------------------
--  DDL for Table D_OCR_COOPERATION_HISTORY
--------------------------------------------------------

  CREATE TABLE "D_OCR_COOPERATION_HISTORY" 
   (	"TKSK_CD" CHAR(6 BYTE) DEFAULT NULL, 
	"HNM_CD" CHAR(3 BYTE) DEFAULT NULL, 
	"DOC_ID" CHAR(8 BYTE), 
	"SRC_FOLDER_NAME" VARCHAR2(255 BYTE), 
	"SRC_IMAGE_FILE_NAME" VARCHAR2(255 BYTE), 
	"OCR_IMAGE_FILE_NAME" VARCHAR2(255 BYTE), 
	"OCR_CSV_IMPORT_DATE" DATE, 
	"INS_USER_ID" VARCHAR2(30 BYTE), 
	"INS_DATE" DATE DEFAULT sysdate, 
	"UPD_USER_ID" VARCHAR2(30 BYTE), 
	"UPD_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;

   COMMENT ON COLUMN "D_OCR_COOPERATION_HISTORY"."TKSK_CD" IS '得意先コード';
   COMMENT ON COLUMN "D_OCR_COOPERATION_HISTORY"."HNM_CD" IS '品名コード';
   COMMENT ON COLUMN "D_OCR_COOPERATION_HISTORY"."DOC_ID" IS '帳票ID';
   COMMENT ON COLUMN "D_OCR_COOPERATION_HISTORY"."SRC_FOLDER_NAME" IS 'オリジナル画像フォルダ名';
   COMMENT ON COLUMN "D_OCR_COOPERATION_HISTORY"."SRC_IMAGE_FILE_NAME" IS 'オリジナル画像ファイル名';
   COMMENT ON COLUMN "D_OCR_COOPERATION_HISTORY"."OCR_IMAGE_FILE_NAME" IS 'OCR連携画像ファイル名';
   COMMENT ON COLUMN "D_OCR_COOPERATION_HISTORY"."OCR_CSV_IMPORT_DATE" IS 'OCR結果取込み日時';
   COMMENT ON COLUMN "D_OCR_COOPERATION_HISTORY"."INS_USER_ID" IS '登録ユーザID';
   COMMENT ON COLUMN "D_OCR_COOPERATION_HISTORY"."INS_DATE" IS '登録日時';
   COMMENT ON COLUMN "D_OCR_COOPERATION_HISTORY"."UPD_USER_ID" IS '更新ユーザID';
   COMMENT ON COLUMN "D_OCR_COOPERATION_HISTORY"."UPD_DATE" IS '更新日時';
   COMMENT ON TABLE "D_OCR_COOPERATION_HISTORY"  IS 'OCR連携履歴';
--------------------------------------------------------
--  DDL for Table M_DOC
--------------------------------------------------------

  CREATE TABLE "M_DOC" 
   (	"TKSK_CD" CHAR(6 BYTE) DEFAULT '000000', 
	"HNM_CD" CHAR(3 BYTE) DEFAULT '000', 
	"DOC_ID" CHAR(8 BYTE), 
	"DOC_NAME" NVARCHAR2(40), 
	"ENTRY_ITEMS_NUM" NUMBER(4,0) DEFAULT 0, 
	"ENTRY_UNIT_NUM" NUMBER(4,0) DEFAULT 10, 
	"DEFAULT_IMAGE_ZOOM_RATE" NUMBER(3,2), 
	"SINGLE_ENTRY_FLAG" CHAR(1 BYTE) DEFAULT '0', 
	"FONT_SIZE" NUMBER(2,0) DEFAULT 12, 
	"OCR_COOPERATION_FLAG" CHAR(1 BYTE) DEFAULT '0', 
	"OCR_CSV_COLUMN_NUM" NUMBER(3,0), 
	"ENTRY_METHOD" CHAR(1 BYTE) DEFAULT '1', 
	"BATCH_EXPORT_FLAG" CHAR(1 BYTE) DEFAULT '0', 
	"DUMMY_IMAGE_FOLDER_NAME" VARCHAR2(255 BYTE), 
	"MIN_ENTRY_UNIT_NUM" NUMBER(4,0), 
	"SORT_ORDER" NUMBER(5,0) DEFAULT 0, 
	"DOC_ID_ENTRY" CHAR(8 BYTE), 
	"IMAGE_MASK_STYLE" CHAR(1 BYTE) DEFAULT '1', 
	"MARGIN_X" NUMBER(3,0), 
	"MARGIN_Y" NUMBER(3,0), 
	"GYOUM_KBN" CHAR(4 BYTE) DEFAULT '****', 
	"IMAGE_MASK_TRANSMITTANCE" NUMBER(3,0), 
	"OCR_IMAGE_COOPERATION_PATH" VARCHAR2(255 BYTE), 
	"NO_ENTRY_FLAG" CHAR(1 BYTE) DEFAULT '0', 
	"PRE_LOGICAL_CHECK_FLAG" CHAR(1 BYTE) DEFAULT '0', 
	"AUTO_LAYOUT_FLAG" CHAR(1 BYTE) DEFAULT '1', 
	"PCIDSS_FLAG" CHAR(1 BYTE) DEFAULT '0', 
	"OCR_IMPORT_1ST_FLAG" CHAR(1 BYTE) DEFAULT '0', 
	"OCR_IMPORT_2ND_FLAG" CHAR(1 BYTE) DEFAULT '0', 
	"BATCH_COMPARE_FLAG" CHAR(1 BYTE) DEFAULT '0', 
	"OCR_IMPORT_UNIT_STATUS" CHAR(1 BYTE) DEFAULT '0', 
	"BATCH_CREATE_UNIT_FLAG" CHAR(1 BYTE) DEFAULT '0', 
	"DUMMY_ITEM_FLAG" CHAR(1 BYTE) DEFAULT '0', 
	"UPD_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;

   COMMENT ON COLUMN "M_DOC"."TKSK_CD" IS '得意先コード';
   COMMENT ON COLUMN "M_DOC"."HNM_CD" IS '品名コード';
   COMMENT ON COLUMN "M_DOC"."DOC_ID" IS '帳票ID';
   COMMENT ON COLUMN "M_DOC"."DOC_NAME" IS '帳票名';
   COMMENT ON COLUMN "M_DOC"."ENTRY_ITEMS_NUM" IS 'エントリ項目数';
   COMMENT ON COLUMN "M_DOC"."ENTRY_UNIT_NUM" IS 'エントリ単位内レコード数';
   COMMENT ON COLUMN "M_DOC"."DEFAULT_IMAGE_ZOOM_RATE" IS '初期イメージ倍率';
   COMMENT ON COLUMN "M_DOC"."SINGLE_ENTRY_FLAG" IS 'シングルエントリフラグ';
   COMMENT ON COLUMN "M_DOC"."FONT_SIZE" IS 'フォントサイズ';
   COMMENT ON COLUMN "M_DOC"."OCR_COOPERATION_FLAG" IS 'OCR連携フラグ';
   COMMENT ON COLUMN "M_DOC"."OCR_CSV_COLUMN_NUM" IS 'OCR_CSVカラム数';
   COMMENT ON COLUMN "M_DOC"."ENTRY_METHOD" IS '入力方法（1:イメージ、2:現物）';
   COMMENT ON COLUMN "M_DOC"."BATCH_EXPORT_FLAG" IS 'バッチテキスト出力フラグ';
   COMMENT ON COLUMN "M_DOC"."DUMMY_IMAGE_FOLDER_NAME" IS 'ダミーイメージフォルダ名';
   COMMENT ON COLUMN "M_DOC"."MIN_ENTRY_UNIT_NUM" IS '最低エントリ数';
   COMMENT ON COLUMN "M_DOC"."SORT_ORDER" IS '表示順';
   COMMENT ON COLUMN "M_DOC"."DOC_ID_ENTRY" IS 'エントリ帳票ID';
   COMMENT ON COLUMN "M_DOC"."IMAGE_MASK_STYLE" IS 'イメージマスクスタイル（R:赤、G:緑、B:青、Z:黒）';
   COMMENT ON COLUMN "M_DOC"."MARGIN_X" IS 'イメージマスクマージン_X座標';
   COMMENT ON COLUMN "M_DOC"."MARGIN_Y" IS 'イメージマスクマージン_Y座標';
   COMMENT ON COLUMN "M_DOC"."GYOUM_KBN" IS '帳票種類GRP';
   COMMENT ON COLUMN "M_DOC"."IMAGE_MASK_TRANSMITTANCE" IS 'イメージマスク透過率';
   COMMENT ON COLUMN "M_DOC"."OCR_IMAGE_COOPERATION_PATH" IS 'OCRイメージ連携フォルダ';
   COMMENT ON COLUMN "M_DOC"."NO_ENTRY_FLAG" IS 'エントリ無しフラグ（OCR結果を納品）';
   COMMENT ON COLUMN "M_DOC"."PRE_LOGICAL_CHECK_FLAG" IS '事前論理チェックフラグ';
   COMMENT ON COLUMN "M_DOC"."AUTO_LAYOUT_FLAG" IS '自動レイアウトフラグ';
   COMMENT ON COLUMN "M_DOC"."PCIDSS_FLAG" IS 'PCIDSS対象フラグ';
   COMMENT ON COLUMN "M_DOC"."OCR_IMPORT_1ST_FLAG" IS 'OCR結果1人目取込みフラグ';
   COMMENT ON COLUMN "M_DOC"."OCR_IMPORT_2ND_FLAG" IS 'OCR結果2人目取込みフラグ';
   COMMENT ON COLUMN "M_DOC"."BATCH_COMPARE_FLAG" IS 'バッチコンペアフラグ';
   COMMENT ON COLUMN "M_DOC"."OCR_IMPORT_UNIT_STATUS" IS 'OCR結果取込み後ステータス';
   COMMENT ON COLUMN "M_DOC"."BATCH_CREATE_UNIT_FLAG" IS 'バッチユニット作成フラグ';
   COMMENT ON COLUMN "M_DOC"."DUMMY_ITEM_FLAG" IS 'ダミー項目有無フラグ';
   COMMENT ON COLUMN "M_DOC"."UPD_DATE" IS '更新日時';
   COMMENT ON TABLE "M_DOC"  IS '帳票マスタ';
--------------------------------------------------------
--  DDL for Table M_CODE_DEFINE
--------------------------------------------------------

  CREATE TABLE "M_CODE_DEFINE" 
   (	"TKSK_CD" CHAR(6 BYTE) DEFAULT NULL, 
	"HNM_CD" CHAR(3 BYTE) DEFAULT NULL, 
	"SECTION" VARCHAR2(100 BYTE), 
	"KEY" VARCHAR2(100 BYTE), 
	"VALUE_1" NVARCHAR2(50), 
	"VALUE_2" NVARCHAR2(50), 
	"VALUE_3" NVARCHAR2(50), 
	"VALUE_4" NVARCHAR2(50), 
	"VALUE_5" NVARCHAR2(50), 
	"DISPLAY_ORDER" NUMBER(3,0), 
	"UPD_DATE" DATE, 
	"SEARCH_KEY" NVARCHAR2(200), 
	"INVALID_FLAG" CHAR(1 BYTE) DEFAULT '0'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;

   COMMENT ON COLUMN "M_CODE_DEFINE"."TKSK_CD" IS '得意先コード';
   COMMENT ON COLUMN "M_CODE_DEFINE"."HNM_CD" IS '品名コード';
   COMMENT ON COLUMN "M_CODE_DEFINE"."SECTION" IS 'セクション';
   COMMENT ON COLUMN "M_CODE_DEFINE"."KEY" IS 'キー';
   COMMENT ON COLUMN "M_CODE_DEFINE"."VALUE_1" IS '値１';
   COMMENT ON COLUMN "M_CODE_DEFINE"."VALUE_2" IS '値２';
   COMMENT ON COLUMN "M_CODE_DEFINE"."VALUE_3" IS '値３';
   COMMENT ON COLUMN "M_CODE_DEFINE"."VALUE_4" IS '値４';
   COMMENT ON COLUMN "M_CODE_DEFINE"."VALUE_5" IS '値５';
   COMMENT ON COLUMN "M_CODE_DEFINE"."DISPLAY_ORDER" IS '表示順';
   COMMENT ON COLUMN "M_CODE_DEFINE"."UPD_DATE" IS '更新日時';
   COMMENT ON COLUMN "M_CODE_DEFINE"."SEARCH_KEY" IS '検索キー';
   COMMENT ON COLUMN "M_CODE_DEFINE"."INVALID_FLAG" IS '無効フラグ';
   COMMENT ON TABLE "M_CODE_DEFINE"  IS 'コード定義マスタ';
--------------------------------------------------------
--  DDL for Table M_ITEM_ID_CONV_OCR
--------------------------------------------------------

  CREATE TABLE "M_ITEM_ID_CONV_OCR" 
   (	"TKSK_CD" CHAR(6 BYTE), 
	"HNM_CD" CHAR(3 BYTE), 
	"DOC_ID" CHAR(8 BYTE), 
	"ITEM_ID_OCR" CHAR(8 BYTE), 
	"ITEM_ID_ENTRY" CHAR(8 BYTE), 
	"ITEM_NAME" NVARCHAR2(100), 
	"TYPE" CHAR(1 BYTE), 
	"MAX_LENGTH" NUMBER(4,0), 
	"IMPORT_1ST_FLAG" CHAR(1 BYTE), 
	"IMPORT_2ND_FLAG" CHAR(1 BYTE), 
	"UPD_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;

   COMMENT ON COLUMN "M_ITEM_ID_CONV_OCR"."TKSK_CD" IS '得意先コード';
   COMMENT ON COLUMN "M_ITEM_ID_CONV_OCR"."HNM_CD" IS '品名コード';
   COMMENT ON COLUMN "M_ITEM_ID_CONV_OCR"."DOC_ID" IS '帳票ID';
   COMMENT ON COLUMN "M_ITEM_ID_CONV_OCR"."ITEM_ID_OCR" IS '項目番号_OCR';
   COMMENT ON COLUMN "M_ITEM_ID_CONV_OCR"."ITEM_ID_ENTRY" IS '項目番号_エントリ';
   COMMENT ON COLUMN "M_ITEM_ID_CONV_OCR"."ITEM_NAME" IS '項目名';
   COMMENT ON COLUMN "M_ITEM_ID_CONV_OCR"."TYPE" IS '属性';
   COMMENT ON COLUMN "M_ITEM_ID_CONV_OCR"."MAX_LENGTH" IS '最大長';
   COMMENT ON COLUMN "M_ITEM_ID_CONV_OCR"."IMPORT_1ST_FLAG" IS '１人目取込フラグ';
   COMMENT ON COLUMN "M_ITEM_ID_CONV_OCR"."IMPORT_2ND_FLAG" IS '２人目取込フラグ';
   COMMENT ON COLUMN "M_ITEM_ID_CONV_OCR"."UPD_DATE" IS '更新日時';
   COMMENT ON TABLE "M_ITEM_ID_CONV_OCR"  IS 'OCR結果取込み定義';
--------------------------------------------------------
--  DDL for Table M_USER
--------------------------------------------------------

  CREATE TABLE "M_USER" 
   (	"USER_ID" VARCHAR2(30 BYTE), 
	"USER_NAME" NVARCHAR2(20), 
	"USER_KBN" CHAR(1 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"VALID_FLAG" CHAR(1 BYTE) DEFAULT '1', 
	"LOGIN_START_DATE" DATE, 
	"LOGIN_IP_ADDRESS" CHAR(12 BYTE), 
	"BUSINESS_ID" CHAR(3 BYTE), 
	"INS_USER_ID" VARCHAR2(30 BYTE), 
	"INS_DATE" DATE DEFAULT sysdate, 
	"UPD_USER_ID" VARCHAR2(30 BYTE), 
	"UPD_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;

   COMMENT ON COLUMN "M_USER"."USER_ID" IS 'ユーザID';
   COMMENT ON COLUMN "M_USER"."USER_NAME" IS 'ユーザ名';
   COMMENT ON COLUMN "M_USER"."USER_KBN" IS 'ユーザ区分';
   COMMENT ON COLUMN "M_USER"."PASSWORD" IS 'パスワード';
   COMMENT ON COLUMN "M_USER"."VALID_FLAG" IS '有効フラグ';
   COMMENT ON COLUMN "M_USER"."LOGIN_START_DATE" IS '最終ログイン日時';
   COMMENT ON COLUMN "M_USER"."LOGIN_IP_ADDRESS" IS 'ログインIPアドレス';
   COMMENT ON COLUMN "M_USER"."BUSINESS_ID" IS '業務ID';
   COMMENT ON COLUMN "M_USER"."INS_USER_ID" IS '登録ユーザID';
   COMMENT ON COLUMN "M_USER"."INS_DATE" IS '登録日時';
   COMMENT ON COLUMN "M_USER"."UPD_USER_ID" IS '更新ユーザID';
   COMMENT ON COLUMN "M_USER"."UPD_DATE" IS '更新日時';
   COMMENT ON TABLE "M_USER"  IS 'ユーザマスタ';
--------------------------------------------------------
--  DDL for Table READING_PAGES
--------------------------------------------------------

  CREATE TABLE "READING_PAGES" 
   (	"ID" CHAR(19 BYTE), 
	"FILE_NAME" VARCHAR2(255 BYTE), 
	"TKSK_CD" VARCHAR2(6 BYTE), 
	"HNM_CD" VARCHAR2(3 BYTE), 
	"DOC_ID" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;

   COMMENT ON COLUMN "READING_PAGES"."ID" IS '帳票ID';
   COMMENT ON COLUMN "READING_PAGES"."FILE_NAME" IS '画像ファイル名';
   COMMENT ON COLUMN "READING_PAGES"."TKSK_CD" IS '得意先コード';
   COMMENT ON COLUMN "READING_PAGES"."HNM_CD" IS '品名コード';
   COMMENT ON COLUMN "READING_PAGES"."DOC_ID" IS '帳票ID';
   COMMENT ON TABLE "READING_PAGES"  IS 'エントリ切り出し画像帳票';
--------------------------------------------------------
--  DDL for Table READING_PARTS
--------------------------------------------------------

  CREATE TABLE "READING_PARTS" 
   (	"READING_PAGES_ID" CHAR(19 BYTE), 
	"COLUNM_NO" NUMBER, 
	"X" NUMBER, 
	"Y" NUMBER, 
	"WIDTH" NUMBER, 
	"HEIGHT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;

   COMMENT ON COLUMN "READING_PARTS"."READING_PAGES_ID" IS '帳票ID';
   COMMENT ON COLUMN "READING_PARTS"."COLUNM_NO" IS '項目ID';
   COMMENT ON COLUMN "READING_PARTS"."X" IS 'X軸';
   COMMENT ON COLUMN "READING_PARTS"."Y" IS 'Y軸';
   COMMENT ON COLUMN "READING_PARTS"."WIDTH" IS '幅';
   COMMENT ON COLUMN "READING_PARTS"."HEIGHT" IS '高さ';
   COMMENT ON TABLE "READING_PARTS"  IS 'エントリ切り出し画像項目';
--------------------------------------------------------
--  DDL for Index D_ENTRY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "D_ENTRY_PK" ON "D_ENTRY" ("ENTRY_UNIT_ID", "RECORD_KBN", "IMAGE_SEQ", "ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;
--------------------------------------------------------
--  DDL for Index D_ENTRY_STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "D_ENTRY_STATUS_PK" ON "D_ENTRY_STATUS" ("ENTRY_UNIT_ID", "RECORD_KBN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;
--------------------------------------------------------
--  DDL for Index D_ENTRY_UNIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "D_ENTRY_UNIT_PK" ON "D_ENTRY_UNIT" ("TKSK_CD", "HNM_CD", "IMAGE_CAPTURE_DATE", "IMAGE_CAPTURE_NUM", "DOC_ID", "ENTRY_UNIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;
--------------------------------------------------------
--  DDL for Index D_ENTRY_UNIT_UIDX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "D_ENTRY_UNIT_UIDX1" ON "D_ENTRY_UNIT" ("ENTRY_UNIT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;
--------------------------------------------------------
--  DDL for Index D_IMAGE_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "D_IMAGE_INFO_PK" ON "D_IMAGE_INFO" ("ENTRY_UNIT_ID", "IMAGE_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;
--------------------------------------------------------
--  DDL for Index D_IMAGE_INFO_UIDX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "D_IMAGE_INFO_UIDX1" ON "D_IMAGE_INFO" ("IMAGE_PATH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;
--------------------------------------------------------
--  DDL for Index D_IMAGE_INFO_UIDX2
--------------------------------------------------------

  CREATE UNIQUE INDEX "D_IMAGE_INFO_UIDX2" ON "D_IMAGE_INFO" ("OCR_IMAGE_FILE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;
--------------------------------------------------------
--  DDL for Index D_OCR_COOPERATION_HISTORY_UIDX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "D_OCR_COOPERATION_HISTORY_UIDX1" ON "D_OCR_COOPERATION_HISTORY" ("OCR_IMAGE_FILE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;
--------------------------------------------------------
--  DDL for Index M_DOC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "M_DOC_PK" ON "M_DOC" ("TKSK_CD", "HNM_CD", "DOC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;
--------------------------------------------------------
--  DDL for Index M_CODE_DEFINE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "M_CODE_DEFINE_PK" ON "M_CODE_DEFINE" ("TKSK_CD", "HNM_CD", "SECTION", "KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;
--------------------------------------------------------
--  DDL for Index M_ITEM_ID_CONV_OCR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "M_ITEM_ID_CONV_OCR_PK" ON "M_ITEM_ID_CONV_OCR" ("TKSK_CD", "HNM_CD", "DOC_ID", "ITEM_ID_OCR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;
--------------------------------------------------------
--  DDL for Index M_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "M_USER_PK" ON "M_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;
--------------------------------------------------------
--  DDL for Index READING_PAGES_UIDX2
--------------------------------------------------------

  CREATE UNIQUE INDEX "READING_PAGES_UIDX2" ON "READING_PAGES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;
--------------------------------------------------------
--  DDL for Index READING_PAGES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "READING_PAGES_PK" ON "READING_PAGES" ("TKSK_CD", "HNM_CD", "DOC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;
--------------------------------------------------------
--  DDL for Index READING_PAGES_UIDX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "READING_PAGES_UIDX1" ON "READING_PAGES" ("FILE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;
--------------------------------------------------------
--  DDL for Index READING_PARTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "READING_PARTS_PK" ON "READING_PARTS" ("READING_PAGES_ID", "COLUNM_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;
--------------------------------------------------------
--  Constraints for Table D_ENTRY
--------------------------------------------------------

  ALTER TABLE "D_ENTRY" MODIFY ("ENTRY_UNIT_ID" NOT NULL ENABLE);
  ALTER TABLE "D_ENTRY" MODIFY ("RECORD_KBN" NOT NULL ENABLE);
  ALTER TABLE "D_ENTRY" MODIFY ("IMAGE_SEQ" NOT NULL ENABLE);
  ALTER TABLE "D_ENTRY" MODIFY ("ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "D_ENTRY" ADD CONSTRAINT "D_ENTRY_PK" PRIMARY KEY ("ENTRY_UNIT_ID", "RECORD_KBN", "IMAGE_SEQ", "ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  Constraints for Table D_ENTRY_STATUS
--------------------------------------------------------

  ALTER TABLE "D_ENTRY_STATUS" MODIFY ("ENTRY_UNIT_ID" NOT NULL ENABLE);
  ALTER TABLE "D_ENTRY_STATUS" MODIFY ("RECORD_KBN" NOT NULL ENABLE);
  ALTER TABLE "D_ENTRY_STATUS" MODIFY ("ENTRY_STATUS" NOT NULL ENABLE);
  ALTER TABLE "D_ENTRY_STATUS" ADD CONSTRAINT "D_ENTRY_STATUS_PK" PRIMARY KEY ("ENTRY_UNIT_ID", "RECORD_KBN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  Constraints for Table D_ENTRY_UNIT
--------------------------------------------------------

  ALTER TABLE "D_ENTRY_UNIT" MODIFY ("TKSK_CD" NOT NULL ENABLE);
  ALTER TABLE "D_ENTRY_UNIT" MODIFY ("HNM_CD" NOT NULL ENABLE);
  ALTER TABLE "D_ENTRY_UNIT" MODIFY ("IMAGE_CAPTURE_DATE" NOT NULL ENABLE);
  ALTER TABLE "D_ENTRY_UNIT" MODIFY ("IMAGE_CAPTURE_NUM" NOT NULL ENABLE);
  ALTER TABLE "D_ENTRY_UNIT" MODIFY ("DOC_ID" NOT NULL ENABLE);
  ALTER TABLE "D_ENTRY_UNIT" MODIFY ("ENTRY_UNIT" NOT NULL ENABLE);
  ALTER TABLE "D_ENTRY_UNIT" MODIFY ("VERIFY_ING_FLAG" NOT NULL ENABLE);
  ALTER TABLE "D_ENTRY_UNIT" ADD CONSTRAINT "D_ENTRY_UNIT_PK" PRIMARY KEY ("TKSK_CD", "HNM_CD", "IMAGE_CAPTURE_DATE", "IMAGE_CAPTURE_NUM", "DOC_ID", "ENTRY_UNIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  Constraints for Table D_IMAGE_INFO
--------------------------------------------------------

  ALTER TABLE "D_IMAGE_INFO" MODIFY ("ENTRY_UNIT_ID" NOT NULL ENABLE);
  ALTER TABLE "D_IMAGE_INFO" MODIFY ("IMAGE_SEQ" NOT NULL ENABLE);
  ALTER TABLE "D_IMAGE_INFO" MODIFY ("IMAGE_PATH" NOT NULL ENABLE);
  ALTER TABLE "D_IMAGE_INFO" MODIFY ("RECORD_KBN_0_ENTRY_FLAG" NOT NULL ENABLE);
  ALTER TABLE "D_IMAGE_INFO" MODIFY ("RECORD_KBN_1_ENTRY_FLAG" NOT NULL ENABLE);
  ALTER TABLE "D_IMAGE_INFO" MODIFY ("RECORD_KBN_2_ENTRY_FLAG" NOT NULL ENABLE);
  ALTER TABLE "D_IMAGE_INFO" MODIFY ("DUMMY_IMAGE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "D_IMAGE_INFO" ADD CONSTRAINT "D_IMAGE_INFO_PK" PRIMARY KEY ("ENTRY_UNIT_ID", "IMAGE_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  Constraints for Table D_OCR_COOPERATION_HISTORY
--------------------------------------------------------

  ALTER TABLE "D_OCR_COOPERATION_HISTORY" MODIFY ("TKSK_CD" NOT NULL ENABLE);
  ALTER TABLE "D_OCR_COOPERATION_HISTORY" MODIFY ("HNM_CD" NOT NULL ENABLE);
  ALTER TABLE "D_OCR_COOPERATION_HISTORY" MODIFY ("DOC_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table M_DOC
--------------------------------------------------------

  ALTER TABLE "M_DOC" MODIFY ("BATCH_COMPARE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "M_DOC" MODIFY ("TKSK_CD" NOT NULL ENABLE);
  ALTER TABLE "M_DOC" MODIFY ("HNM_CD" NOT NULL ENABLE);
  ALTER TABLE "M_DOC" MODIFY ("DOC_ID" NOT NULL ENABLE);
  ALTER TABLE "M_DOC" MODIFY ("ENTRY_ITEMS_NUM" NOT NULL ENABLE);
  ALTER TABLE "M_DOC" MODIFY ("ENTRY_UNIT_NUM" NOT NULL ENABLE);
  ALTER TABLE "M_DOC" MODIFY ("DEFAULT_IMAGE_ZOOM_RATE" NOT NULL ENABLE);
  ALTER TABLE "M_DOC" MODIFY ("SINGLE_ENTRY_FLAG" NOT NULL ENABLE);
  ALTER TABLE "M_DOC" MODIFY ("FONT_SIZE" NOT NULL ENABLE);
  ALTER TABLE "M_DOC" MODIFY ("OCR_COOPERATION_FLAG" NOT NULL ENABLE);
  ALTER TABLE "M_DOC" ADD CONSTRAINT "M_DOC_PK" PRIMARY KEY ("TKSK_CD", "HNM_CD", "DOC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
  ALTER TABLE "M_DOC" MODIFY ("ENTRY_METHOD" NOT NULL ENABLE);
  ALTER TABLE "M_DOC" MODIFY ("BATCH_EXPORT_FLAG" NOT NULL ENABLE);
  ALTER TABLE "M_DOC" MODIFY ("NO_ENTRY_FLAG" NOT NULL ENABLE);
  ALTER TABLE "M_DOC" MODIFY ("PRE_LOGICAL_CHECK_FLAG" NOT NULL ENABLE);
  ALTER TABLE "M_DOC" MODIFY ("AUTO_LAYOUT_FLAG" NOT NULL ENABLE);
  ALTER TABLE "M_DOC" MODIFY ("PCIDSS_FLAG" NOT NULL ENABLE);
  ALTER TABLE "M_DOC" MODIFY ("OCR_IMPORT_1ST_FLAG" NOT NULL ENABLE);
  ALTER TABLE "M_DOC" MODIFY ("OCR_IMPORT_2ND_FLAG" NOT NULL ENABLE);
  ALTER TABLE "M_DOC" MODIFY ("OCR_IMPORT_UNIT_STATUS" NOT NULL ENABLE);
  ALTER TABLE "M_DOC" MODIFY ("BATCH_CREATE_UNIT_FLAG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table M_CODE_DEFINE
--------------------------------------------------------

  ALTER TABLE "M_CODE_DEFINE" MODIFY ("TKSK_CD" NOT NULL ENABLE);
  ALTER TABLE "M_CODE_DEFINE" MODIFY ("HNM_CD" NOT NULL ENABLE);
  ALTER TABLE "M_CODE_DEFINE" MODIFY ("SECTION" NOT NULL ENABLE);
  ALTER TABLE "M_CODE_DEFINE" MODIFY ("KEY" NOT NULL ENABLE);
  ALTER TABLE "M_CODE_DEFINE" ADD CONSTRAINT "M_CODE_DEFINE_PK" PRIMARY KEY ("TKSK_CD", "HNM_CD", "SECTION", "KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  Constraints for Table M_ITEM_ID_CONV_OCR
--------------------------------------------------------

  ALTER TABLE "M_ITEM_ID_CONV_OCR" MODIFY ("TKSK_CD" NOT NULL ENABLE);
  ALTER TABLE "M_ITEM_ID_CONV_OCR" ADD CONSTRAINT "M_ITEM_ID_CONV_OCR_PK" PRIMARY KEY ("TKSK_CD", "HNM_CD", "DOC_ID", "ITEM_ID_OCR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
  ALTER TABLE "M_ITEM_ID_CONV_OCR" MODIFY ("ITEM_ID_OCR" NOT NULL ENABLE);
  ALTER TABLE "M_ITEM_ID_CONV_OCR" MODIFY ("DOC_ID" NOT NULL ENABLE);
  ALTER TABLE "M_ITEM_ID_CONV_OCR" MODIFY ("HNM_CD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table M_USER
--------------------------------------------------------

  ALTER TABLE "M_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "M_USER" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "M_USER" MODIFY ("USER_KBN" NOT NULL ENABLE);
  ALTER TABLE "M_USER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "M_USER" MODIFY ("VALID_FLAG" NOT NULL ENABLE);
  ALTER TABLE "M_USER" ADD CONSTRAINT "M_USER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  Constraints for Table READING_PAGES
--------------------------------------------------------

  ALTER TABLE "READING_PAGES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "READING_PAGES" MODIFY ("TKSK_CD" NOT NULL ENABLE);
  ALTER TABLE "READING_PAGES" MODIFY ("HNM_CD" NOT NULL ENABLE);
  ALTER TABLE "READING_PAGES" MODIFY ("DOC_ID" NOT NULL ENABLE);
  ALTER TABLE "READING_PAGES" ADD CONSTRAINT "READING_PAGES_PK" PRIMARY KEY ("TKSK_CD", "HNM_CD", "DOC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  Constraints for Table READING_PARTS
--------------------------------------------------------

  ALTER TABLE "READING_PARTS" MODIFY ("READING_PAGES_ID" NOT NULL ENABLE);
  ALTER TABLE "READING_PARTS" MODIFY ("COLUNM_NO" NOT NULL ENABLE);
  ALTER TABLE "READING_PARTS" ADD CONSTRAINT "READING_PARTS_PK" PRIMARY KEY ("READING_PAGES_ID", "COLUNM_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
